services:
  db:
    container_name: ${DEPLOY_ENV:-staging}-db
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    container_name: ${DEPLOY_ENV:-staging}-backend
    image: scrip/tgc-nov25-back:${DEPLOY_ENV:-staging}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      GRAPHQL_SERVER_PORT: 4000
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", "curl -sS -o /dev/null http://localhost:4000 || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 10

  frontend:
    container_name: ${DEPLOY_ENV:-staging}-frontend
    image: scrip/tgc-nov25-front:${DEPLOY_ENV:-staging}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 10

  gateway:
    container_name: ${DEPLOY_ENV:-staging}-gateway
    build:
      context: gateway
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: always
    ports:
      - ${GATEWAY_PORT-80}:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  db-data:
    name: "${DEPLOY_ENV:-staging}-db-data"
