services:
  db:
    container_name: prod-db-1
    image: postgres:15-alpine
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-postgres}
      PGUSER: ${DB_USER-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - prodDB:/var/lib/postgresql/data

  backend:
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_PASS: ${DB_PASS-postgres}
      DB_PORT: ${DB_PORT-5432}
      DB_USER: ${DB_USER-postgres}
      DB_NAME: ${DB_NAME-postgres}
      GRAPHQL_SERVER_PORT: ${GRAPHQL_SERVER_PORT-4001}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      NODE_ENV: ${NODE_ENV:-production}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-changeme}
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    image: scrip/tgc-nov-25-back:staging

  frontend:
    stop_grace_period: 0s
    image: scrip/tgc-nov-25-front:staging

  gateway:
    restart: always
    stop_grace_period: 0s
    build:
      context: gateway
    ports:
      - ${GATEWAY_PORT-80}:80

volumes:
  prodDB: