services:
  db:
    image: postgres:18.1-alpine3.23
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    env_file:
      - .env.production
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    image: scrip/tgc-nov-25-back:${DEPLOY_ENV:-staging}

  frontend:
    stop_grace_period: 0s
    image: scrip/tgc-nov-25-front:${DEPLOY_ENV:-staging}

  gateway:
    container_name: ${DEPLOY_ENV:-staging}-gateway
    restart: always
    stop_grace_period: 0s
    build:
      context: gateway
    ports:
      - ${GATEWAY_PORT-80}:80

volumes:
  db-data:
    name: "${DEPLOY_ENV:-staging}-db-data"
