services:
  testDB:
    image: postgres:18.1-alpine3.23
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 10
    stop_grace_period: 1s
    restart: always
    tmpfs: /var/lib/postgresql
    ports:
      - 5433:5432

  backend:
    stop_grace_period: 0s
    env_file:
      - ./.env
    build: ../backend
    ports:
      - 4000:4000
    volumes:
      - ../backend/src:/app/src
    environment:
      - DB_HOST=testDB
      - TEST_DB_PORT=5432
    healthcheck:
      test: 'curl --fail --request GET -H ''content-type:application/json'' --url ''http://localhost:4000/?query=%7B__typename%7D'''
      interval: 1s
      timeout: 2s
      retries: 30
    depends_on:
      testDB:
        condition: service_healthy

  frontend:
    stop_grace_period: 0s
    build: '../frontend'
    environment:
      - NEXT_PUBLIC_GRAPHQL_API_URL=http://localhost:4000
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy