name: Compile and push client and server to staging environment

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: ComicScrip/the-good-corner-nov23/.github/workflows/tests-frontend.yml@main

  build-and-push-server:
    uses: ComicScrip/the-good-corner-nov23/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ${{ secrets.DOCKERHUB_USERNAME }}/tgc-nov25-back:staging

  build-and-push-client:
    needs:
      - client-tests
    uses: ComicScrip/the-good-corner-nov23/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ${{ secrets.DOCKERHUB_USERNAME }}/tgc-nov25-back:staging