name: Compile and push client and server to staging environment

on:
  push:
    branches: ["prepare-deploy"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/test-frontend.yml@prepare-deploy

  build-and-push-server:
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/build-backend.yml@prepare-deploy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: scrip/tgc-nov25-back:staging

  build-and-push-client:
    needs:
      - client-tests
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/build-frontend.yml@prepare-deploy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: scrip/tgc-nov25-back:staging