name: Compile and push client and server to staging environment

on:
  push:
    branches: ["dev"]

jobs:
  client-tests:
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/test-frontend.yml@dev

  build-and-push-server:
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/build-backend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: scrip/tgc-nov25-back:staging

  build-and-push-client:
    needs:
      - client-tests
    uses: ComicScrip/the-good-corner-nov25/.github/workflows/build-frontend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: scrip/tgc-nov25-front:staging

  notify-vps:
    needs:
      - build-and-push-server
      - build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook on VPS
        run: |
          curl -X POST \
            -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://ops.thegoodcorner.duckdns.org/hooks/redeploy-tgc-staging